git add bitcoin-outputs/blockchair_bitcoin_outputs_20140908.tsv.gz & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140909.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140911.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140912.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140913.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140914.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140915.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140916.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140918.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140919.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140920.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140921.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140923.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140925.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140927.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140928.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20140930.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141002.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141003.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141005.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141007.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141008.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141009.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141010.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141011.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141012.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141014.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141015.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141017.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141018.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141019.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141021.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141023.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141024.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141025.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141027.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141029.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141031.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141102.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141104.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141106.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141108.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141109.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141111.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141113.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141115.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141116.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141118.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141120.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141122.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141123.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141125.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141127.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141129.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141130.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141202.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141204.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141206.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141207.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141209.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141211.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141213.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141214.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141216.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141218.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141220.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141222.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141224.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141225.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141226.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141227.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141229.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20141230.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150101.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150102.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150104.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150106.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150108.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150110.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150112.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150114.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150116.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150118.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150120.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150122.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150124.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150126.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150128.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150129.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150131.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150202.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150204.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150206.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150208.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150210.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150212.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150214.tsv.gz  & git commit -m "add" & git push
git add bitcoin-outputs/blockchair_bitcoin_outputs_20150216.tsv.gz  & git commit -m "add" & git push
git add bitcoin-transactions/2014/ & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20150226.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20150507.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20150531.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20150903.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20150911.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20160124.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20190427.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20190823.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20191105.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20191111.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20200410.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20200416.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20200527.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20200616.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20200623.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20201128.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20201130.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20201216.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20210111.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20210113.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20210115.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20210126.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20210901.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20211020.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20211103.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20211109.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20211116.tsv.gz   & git commit -m "add" & git push
git add bitcoin-transactions/blockchair_bitcoin_transactions_20211128.tsv.gz   & git commit -m "add" & git push